# Generated by Django 3.1.1 on 2021-01-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subworkpackage_date_of_creation_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkpackage',
            name='date_of_creation_temp',
        ),
    ]
