# Generated by Django 3.1.1 on 2021-01-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state1',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
