# Generated by Django 3.1.1 on 2021-02-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210126_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
    ]
