# Generated by Django 3.1.1 on 2021-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workpackage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
