# Generated by Django 3.1.1 on 2021-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210202_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='border_color',
            field=models.CharField(default='#ffffff', max_length=8),
        ),
    ]
