# Generated by Django 3.1.1 on 2021-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_border_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='efforts_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='efforts_planned',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='priority',
            field=models.IntegerField(choices=[('LOW', 1), ('MEDIUM', 2), ('HIGH', 3)], default=1),
        ),
    ]
