# Generated by Django 3.1.1 on 2021-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210208_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
